### ISSUE TITLE
运行这个程序的时候，只有一个图片，是那里操作错了吗

### ISSUE THREAD

**Issue by wangwenqiangGitHub** [RicheyHuang/BoustrophedonCellularDecompositionPathPlanning#8]

**Comment by RicheyHuang** [comment]
@wangwenqiangGitHub 试一下逐个测试用例跑一下？我这边目前还没出现这个问题

**Comment by wangwenqiangGitHub** [comment]
> @wangwenqiangGitHub 试一下逐个测试用例跑一下？我这边目前还没出现这个问题

我逐个测试了，也还是不行，只是有一个图片窗口，没有README中的动图的效果

**Comment by RicheyHuang** [comment]
@wangwenqiangGitHub 出来图片窗口后，要敲一下空格才会开始运行的，有试过吗？

**Comment by wangwenqiangGitHub** [comment]
哦哦，ok了，感谢分享
